name: PySpark ETL CI (unittest)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    name: Run PySpark Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyspark

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "test_*.py"

  deploy:
    name: Deploy PySpark ETL
    runs-on: ubuntu-latest
    needs: test   # s'exécute seulement si le job 'test' réussit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyspark

      - name: Run deployment script
        run: |
          echo "Déploiement du pipeline ETL ici"
          # Ici tu peux appeler ton script de déploiement réel
